hashicorp/hcl2

- gohcl/decode_test.go
- gohcl/schema.go
- gohcl/schema_test.go
Added `optional` tag for attributes on structs.  In the following example, MiddleName is marked as optional and after decoding the field `MiddleName` on the Person object would be an empty string.  For situations where HCL is used for configuration optional rather than a pointer is more explicit.  It allows parsing of config with validation without needing to mix value and reference types for simple objects.
```go
struct Person struct {
FirstName     string `hcl:"first_name"`
MiddleName string `hcl:"middle_name,optional"`
Surname       string `hcl:"surname"`
}
```
```hcl
person {
first_name = "Nic"
surname    = "Jackson"
}
```
I was not sure where to place the docs for this, happy to add docs as an additional commit.
Signed-off-by: nicholasjackson <jackson.nic@gmail.com>
> Added struct tag optional for gohcl

- hcl/hclsyntax/parser_test.go
- hcl/json/parser_test.go
`github.com/go-test/deep` has pretty low default settings for how deeply it should inspect nested structures. As an effect we were silently ignoring some differences.
Also see https://github.com/go-test/deep/issues/17
I'm not sure if there's a better way/place where to set `MaxDepth` or whether this depth is appropriate, it's just an arbitrary number.
I'm open to suggestions.
I'm also adding a test which I used to invalidate my assumption that we parse `func()[idx]` incorrectly - i.e. there is nothing to fix, but I just thought it would be useful to have such test in place for the future, just in case.
> hclsyntax: Add test for 'func()[idx]' syntax

- hcl/hclsyntax/navigation.go
- hcl/hclsyntax/navigation_test.go
- hcl/hclsyntax/structure.go
- hcled/navigation.go
This can be used for looking up range of block definition so that we can render it alongside attribute-agnostic errors.
I'm willing to add some tests to cover this new functionality and also `ContextString`, but I'd like to hear whether this is a good idea at all 😃
> hcled: Introduce ContextDefRange

- hcl/merged.go
- hcl/merged_test.go
The `mergedLeftovers` slice wasn't being appended with anything so the remaining content after a `PartialContent` was empty. I also added some test cases to cover the change.
> hcl/merged: Fix PartialContent used on merged bodies

- hclpack/structure.go
- hclpack/structure_test.go
Fixes an issue where a nested block would be decoded incorrectly, the
body of the last decoded block overwrites the previously decoded ones.
This was caused by the block being assigned on the stack in the `for`
loop; when the block is converted to a *hcl.Block, the pointer to Body
will always point to the same block. This caused decoding a new block to
overwrite the bodies of any previously decoded blocks.
_This is my first PR here, if there's anything else you'd like to see here please let me know._
Fixes #72
> hclpack: fix hclpack decoding nested body

- hclpack/structure.go
- hclpack/structure_test.go
Fixes setting the MissingItemRange on the remaining body when a
`*hclpack.Body` is partially decoded. Otherwise when the remaining body is
decoded with missing fields, the diagnostic cannot point to where they
should be set.
> hclpack: fix missing range on remaining body

- hclpack/positions_packed.go
- hclpack/positions_packed_test.go
When marshalling positions into binary, the current file index was not stored. Because of this, a `;` was inserted multiple times for each file, even if the file did not change.
When unmarshalling, the `fileIdx` determined by number of `;` was ignored. Thus, if there were more than one file, all the positions would still point to the first file.
This was likely intended to be there in the first place but was just missed.
> hclpack: fix marshalling binary file index positions

- hclwrite/format.go
- hclwrite/format_test.go
closes #65
- add missing edge case for two interpolated items next to each other
- add tests for both quote and heredoc cases
> hclwrite: fix space being added between interpolated items

- hcl/hclsyntax/parser.go
- hcl/hclsyntax/parser_test.go
It turns out that some people separate argument definitions with commas even when these are each on new lines.
Here's a [real example](https://github.com/terraform-providers/terraform-provider-fastly/blob/79c4eeba23a8a5ef2753c8404a48ba3bb2a2092b/fastly/resource_fastly_service_v1_bigquerylogging_test.go#L145-L152) I found in acceptance test of the Fastly provider while attempting to upgrade it:
```hcl
resource "fastly_service_v1" "foo" {
name = "..."
bigquerylogging {
name       = "%s"
email      = "email@example.com",
secret_key = "secretKey",
project_id = "example-gcp-project"
dataset    = "example-bq-dataset"
table      = "example-bq-table"
}
}
```
Hence I think this case deserves a special error message.
> hcl/hclsyntax: Improve error reporting for comma-separated args

- hcl/json/structure.go
- hcl/json/structure_test.go
This treats `null` JSON values for block attributes as if they were not
specified, for example:
```json
{
"resource": null,
}
```
will parse as having found no `resource` blocks.
> json: Allow null values for block attributes

- hcl/json/structure.go
- hcl/json/structure_test.go
Evaluate json null values as cty.Null, rather than as unknown value.
Using DynamicPseudoType as the null type as a placeholder for the null
type.  Callers may convert the type against schema to get the concrete
type.
> json: Eval json null values as cty.Null

- hcl/hclsyntax/structure.go
Previously, `hclsyntax` `MissingItemRange()` function returned a zero-length
range anchored at the end of the block in question. This commit changes
that to the beginning of the block. In practice, the end of a block is
generally just a "}" and not very useful in error messages.
Fixes #93
> hclsyntax: return the starting position of a missing attr, not the end.

- hclpack/structure.go
Fixes an issue where the name range may be incorrect in case there are multiple attributes and one of them is wrong. Another attribute's name range could overwrite the previous one as the attr variable is overwritten in the for loop.
The fix is essentially the same as https://github.com/hashicorp/hcl2/pull/73
_Note: there are no tests for this but that's mostly because there were no existing tests for checking diagnostics._
> hclpack: Fix name range for unsupported attribute

- hcl/json/scanner.go
- hcl/json/scanner_test.go
There is a bug in json scanner while scanning an ill-formed document like this one:
```json
&
```
The scanner hangs in infinite loop, and, sometimes panics with memory allocation error.
The reason is the `byteCanStartNumber`  function (`hcl/json/scanner.go`), where alphabetical character check is performed like this:
```go
case b >= 'a' || b <= 'z' || b >= 'A' || b <= 'Z':
return true
```
The check passes for any character, but only ill-formed documents are affected by this, because the scan function tries to scan a keyword after all other lexemmes. The result is that the scanKeyword function returns a token of zero length and slice nothing from the buffer. The buffer remains the same and on the next iteration a keyword will be scanned again, yielding an infinite loop.
I've fixed that and …
> Fix incorrect alphabetical check in json scanner

- ext/dynblock/expand_body.go
- ext/dynblock/expand_body_test.go
- ext/dynblock/unknown_body.go
Previously our behavior for an unknown for_each was to produce a single block whose content was the result of evaluating content with the iterator set to `cty.DynamicVal`. That produced a reasonable idea of the content, but the number of blocks in the result was still not accurate, and that can present a problem for applications that use unknown values to predict the overall shape of a not-yet-complete structure.
We can't return an unknown block via the HCL API, but to make that situation easier to recognize by callers we'll now go a little further and force _all_ of the leaf attributes in such a block to be unknown values, even if they are constants in the configuration. This allows a calling application that is making predictions to use a single object whose leaves are all unknown as a …
> ext/dynblock: Stub out contents when for_each is unknown

- go.mod
- go.sum
This introduces only some minor bugfixes compared to the commit we selected before; the main goal here is to be on an actual tagged release rather than an arbitrary commit.
The additional changes this implies have been shipped in Terraform v0.12.0, so they have been tested in a real application as well as in HCL's own tests.
> dependencies: go get github.com/zclconf/go-cty@v1.0.0

- hcl/json/structure.go
- hcl/json/structure_test.go
Fix a bug where diagnostics found when evaluating array individual
elements are ignored, resulting in suppressed errors.
Nomad observed this issue in https://github.com/hashicorp/nomad/issues/5694.
> return array value evaluation diagnostics

- hcl/hclsyntax/expression_template.go
- hcl/hclsyntax/expression_test.go
- hcl/hclsyntax/parser.go
- hcl/traversal_for_expr.go
A sequence like `"foo"` is represented in the AST as a `TemplateExpr` with a single string literal inside rather than as a string literal node directly, so we need to recognize that situation during parsing and treat it as a special case so we can get the intended behavior of representing that index as a traversal step rather than as a dynamic index operation.
Most of the time this distinction doesn't matter, but it's important for static analysis use-cases. In particular, `hcl.AbsTraversalForExpr` will now accept an expression like `foo["bar"]` where before it would've rejected it.
This also includes a better error message for when an expression cannot be recognized as a single traversal. There isn't really any context here to return a direct reference to the construct that was …
> hclsyntax: Parse indexing brackets with a string literal as a traversal

- hcl/hclsyntax/expression.go
- hcl/hclsyntax/expression_test.go
The type unification done when evaluating a conditional normally needs
to return a DynamicPseudoType when either condition is dynamic. However,
a null dynamic value represents a known value of the desired type rather
than an unknown type, and we can be certain that it is convertible to
the desired type during the final evaluation.  Rather than unifying
types against nulls, directly assign the needed conversion when
evaluating the conditional.
> Expect correct type from a conditional with nulls

- hcl/hclsyntax/expression.go
- hcl/hclsyntax/expression_test.go
If an expression in a conditional contains a DynamicVal, we know that
the opposing condition can pass through with no conversion since
converting to a DynamicPseudoType is a noop. We can also just pass
through the Dynamic val, since it is unknown and can't be converted.
> ensure correct type in conditionals w/ DynamicVal

- cmd/hcldec/spec-format.md
When I tried a spec with quoted types, I got this error:
`A type is required, not string.`
Later in the document, the types don’t have quotes, so I figured that’s what’s expected.
> Remove incorrect quotes around types in examples

- hcl/structure.go
Fixes a couple minor typos i noticed while reading the docs for `Body`
> hcl: fix minor typos in docs

- hclwrite/format.go
- hclwrite/format_test.go
Potential fix for #106.
`linesForFormat` function already put all tokens in one heredoc into one `formatLine` instance, so `formatIndent` function does not need to go through multiple lines to find the corresponding `TokenCHeredoc`. Instead, it can just ignore the whole line.
> hclwrite: Fix improper indent calculation inside heredocs

- hclwrite/format.go
- hclwrite/format_test.go
Fix for hashicorp/terraform#21434.
Currently `linesForFormat()` waits for `TokenCHeredoc` to appear in a different line after finding `TokenOHeredoc`. It never happens, however, since `scanTokens()` does not produce `TokenNewline` inside heredocs so all tokens between `TokenOHeredoc` and `TokenCHeredoc` are put inside the same line.
Incorrect eq sign alignment happened because inHeredoc flag never set back to `false` then the following `line.assign` calculations were skipped.
>  hclwrite: Fix heredocs never close during format

- hcl/hclsyntax/expression_test.go
- specsuite/tests/expressions/heredoc.hcl
- specsuite/tests/expressions/heredoc.t
>These tests pass, but they close what's effectively a gap in the test
>coverage wherein nothing was ensuring that the whitespace prefix
>trimming behavior still gave the same/correct output with blank lines
>in the middle.
>I made these tests because nomad templates were behaving oddly, only
>to discover that nomad has a mix of both hcl1 and hcl2 in it!
>Fortunately, hcl2's behavior is correct, but it should stay that way.
> Add test cases for multiline heredocs

- hclwrite/format.go
- hclwrite/format_test.go
Fixes https://github.com/hashicorp/terraform/issues/22356
If we format the following code, will get the following results:
**input**
```hcl
"%{if true}${var.foo}%{endif}"
```
**result**
```hcl
"%{if true}${var.foo} %{endif}"
```
This is a different string, so do not add a space before the `%{`. This pull request changes the handling of `TokenTemplateControl` token to avoid adding an extra space.
> hclwrite: Do not add spaces before TokenTemplateControl

- go.mod
- go.sum
This is to prevent potential false positives by bringing in this specific patch:
https://github.com/go-test/deep/pull/23
> deps: Bump github.com/go-test/deep to 1.0.3
